import type { Body } from "../core/ephemeris";
import type { Sign } from "../natal/zodiac";

export interface HouseDeepDive {
  house: number;
  name: string;
  meaning: string;
  psychology: string;
  strengths: string;
  weaknesses: string;
  lifeLessons: string;
  opportunities: string;
  blindSpots: string;
  timing: string;
  evolution: string;
  reflectionQuestions: string[];
  practicalRecommendations: string[];
}

export const HOUSE_DEEP_DIVES: Record<number, HouseDeepDive> = {
  1: {
    house: 1,
    name: "Identity & Self",
    meaning: "Your body, appearance, instinctive style, and the interface between you and the world. The chart's steering wheel.",
    psychology: "How safe you feel simply being seen. First-house wounds show as identity confusion; first-house gifts as effortless presence.",
    strengths: "Self-starting energy, personal brand potential, the ability to reinvent yourself.",
    weaknesses: "Over-identification with image; taking everything personally; leading with persona instead of substance.",
    lifeLessons: "Learning that identity is built by action, not introspection alone — you discover who you are by doing.",
    opportunities: "Any arena where you personally are the product: leadership, performance, personal brands, athletics.",
    blindSpots: "How you actually come across versus how you intend to. Ask three honest people.",
    timing: "Activated in 1st-house profection years (ages 12, 24, 36, 48, 60) and whenever transits cross your Ascendant.",
    evolution: "From self-consciousness → self-definition → self-expression in service of something larger.",
    reflectionQuestions: [
      "Where am I performing a version of myself I've outgrown?",
      "What would I attempt if being seen failing didn't scare me?",
    ],
    practicalRecommendations: [
      "Invest in your physical vitality first — everything in this house runs on the body.",
      "Update your public presentation (bio, wardrobe, headshots) whenever you level up internally; misalignment here costs opportunities.",
    ],
  },
  2: {
    house: 2,
    name: "Money, Assets & Self-Worth",
    meaning: "Income, possessions, financial psychology, and the felt sense of your own value. What you own — and what owns you.",
    psychology: "Money behavior here is self-worth made visible. Under-earning, over-spending and under-charging are 2nd-house wounds wearing financial costumes.",
    strengths: "Resource-building instinct, the capacity to turn talent into income, sensuous appreciation of quality.",
    weaknesses: "Scarcity loops, hoarding or compulsive spending, tying identity to net worth.",
    lifeLessons: "Charging what you're worth without apology; building assets instead of only earning wages.",
    opportunities: "Ownership: equity, intellectual property, real assets, businesses. This house rewards owning over renting your time.",
    blindSpots: "Unexamined money scripts inherited from family — audit what 'people like us' were taught about wealth.",
    timing: "2nd-house profection years (ages 1, 13, 25, 37, 49, 61); Venus and Jupiter transits through this house mark income windows.",
    evolution: "From earning to keep score → earning to build freedom → wealth as a tool for meaning.",
    reflectionQuestions: [
      "What did I learn about money before age ten, and is it still running the show?",
      "What do I produce that could earn while I sleep?",
    ],
    practicalRecommendations: [
      "Automate saving/investing before discretionary spending — willpower is not a 2nd-house strategy.",
      "Raise your rates or ask for the raise this quarter; document the value you create first.",
      "Own something: start with index equity, then assets aligned with your chart's strong houses.",
    ],
  },
  3: {
    house: 3,
    name: "Mind, Voice & Skills",
    meaning: "Communication, learning style, siblings, local environment, writing, and the daily traffic of ideas.",
    psychology: "Whether your voice was welcomed as a child echoes here. A strong 3rd house needs to articulate to metabolize life.",
    strengths: "Verbal agility, teachability, networking through information, content creation.",
    weaknesses: "Scattered attention, gossip, mistaking information for wisdom.",
    lifeLessons: "Focus: choosing which of your many interests deserves mastery.",
    opportunities: "Writing, media, teaching, sales, trade — any leverage of language.",
    blindSpots: "Listening. The 3rd house talks; mastery arrives when it also hears.",
    timing: "3rd-house profection years (ages 2, 14, 26, 38, 50); Mercury transits and retrogrades hit this house's agenda.",
    evolution: "From collecting facts → forming a voice → having something to say that changes people.",
    reflectionQuestions: ["Which skill, if mastered, would multiply everything else I do?"],
    practicalRecommendations: [
      "Publish regularly in any medium — this house compounds through repetition.",
      "Batch communication; protect deep-work hours from its constant chatter.",
    ],
  },
  4: {
    house: 4,
    name: "Home, Family & Foundations",
    meaning: "Your literal home, family of origin, ancestry, private self, and emotional foundation. The root system.",
    psychology: "The template of safety formed early. Career (10th) can only rise as high as this taproot is deep.",
    strengths: "Capacity for belonging, family loyalty, real-estate instinct, emotional depth.",
    weaknesses: "Repeating inherited patterns; confusing familiarity with safety.",
    lifeLessons: "Building the home you needed rather than recreating the one you had.",
    opportunities: "Real estate, family enterprises, working from home, healing generational patterns — being the one who breaks the cycle.",
    blindSpots: "How much your living environment is silently shaping your output and mood.",
    timing: "4th-house profection years (ages 3, 15, 27, 39, 51); lunations here mark home/family turning points.",
    evolution: "From leaving home → understanding home → becoming home for yourself and others.",
    reflectionQuestions: ["What family pattern stops with me?", "Does my home restore me or drain me?"],
    practicalRecommendations: [
      "Treat your home as infrastructure: optimize light, quiet, and one space that is entirely yours.",
      "Map your family's money/relationship patterns across three generations; awareness is half the healing.",
    ],
  },
  5: {
    house: 5,
    name: "Creativity, Romance & Joy",
    meaning: "Self-expression, art, play, romance, children, speculation — everything you create that carries your signature.",
    psychology: "The inner child's status report. Blocked 5th house = life that works but doesn't feel alive.",
    strengths: "Creative output, charisma, romantic generosity, willingness to risk on yourself.",
    weaknesses: "Drama addiction, validation-seeking, gambling (literal or emotional).",
    lifeLessons: "Creating for the joy of it before the market of it; loving without performing.",
    opportunities: "Creative businesses, entertainment, working with children, calculated speculation.",
    blindSpots: "Joy deficit disguised as busyness. Fun is not a reward for finished work; it's fuel.",
    timing: "5th-house profection years (ages 4, 16, 28, 40, 52); Venus transits here light romance and creative wins.",
    evolution: "From wanting applause → expressing truth → creating things that outlive you.",
    reflectionQuestions: ["What did I love making at age nine?", "Where has my life become all maintenance and no play?"],
    practicalRecommendations: [
      "Schedule creation before consumption: one hour of making before feeds and inboxes.",
      "Take the creative risk small and public rather than grand and private.",
    ],
  },
  6: {
    house: 6,
    name: "Work, Health & Routines",
    meaning: "Daily work, craft, service, health habits, and the systems that quietly determine everything else.",
    psychology: "The relationship between effort and worth. 6th-house wounds appear as over-functioning, burnout, or body symptoms carrying unspoken messages.",
    strengths: "Craftsmanship, reliability, process intelligence, healing ability.",
    weaknesses: "Perfectionism, servitude without boundaries, ignoring the body until it shouts.",
    lifeLessons: "Sustainable rhythm over heroic sprints; service from overflow, not depletion.",
    opportunities: "Operational excellence, health professions, craft mastery, building systems that scale you.",
    blindSpots: "The body keeps score here first — stress shows in this house before you admit it mentally.",
    timing: "6th-house profection years (ages 5, 17, 29, 41, 53); Mars transits here spike workload and inflammation alike.",
    evolution: "From working hard → working well → work as devotion.",
    reflectionQuestions: ["Which daily habit is compounding against me?", "What would my body say if it wrote me a memo?"],
    practicalRecommendations: [
      "Fix sleep first; every other 6th-house metric follows it.",
      "Systematize the repeatable 80% of your work to protect energy for the meaningful 20%.",
    ],
  },
  7: {
    house: 7,
    name: "Partnership & The Other",
    meaning: "Marriage, business partners, close collaborators, open enemies — every one-to-one mirror.",
    psychology: "What you disown in yourself you meet in partners. The 7th house is where projection goes to be recognized.",
    strengths: "Alliance-building, diplomacy, the multiplication that comes from true partnership.",
    weaknesses: "Losing yourself in others, chronic accommodation, attracting what you refuse to become.",
    lifeLessons: "Choosing partners consciously instead of magnetically; staying whole while deeply joined.",
    opportunities: "Strategic partnerships, client-facing mastery, marriage as a growth engine.",
    blindSpots: "Your repeating 'type' — in lovers and business partners — is a map of your own unintegrated material.",
    timing: "7th-house profection years (ages 6, 18, 30, 42, 54); outer-planet transits here reliably restructure commitments.",
    evolution: "From needing completion → choosing collaboration → partnership as spiritual practice.",
    reflectionQuestions: ["What quality do all my significant others share — and where is it in me?"],
    practicalRecommendations: [
      "Write your partnership criteria while single/uncommitted; decide in clarity, not chemistry.",
      "In business, contract for the divorce before the wedding: exit terms while everyone is friends.",
    ],
  },
  8: {
    house: 8,
    name: "Depth, Shared Resources & Transformation",
    meaning: "Intimacy, other people's money, debt, inheritance, taxes, crisis, death-and-rebirth cycles, psychological depth.",
    psychology: "Where control meets surrender. 8th-house material is whatever you'd rather not talk about — which is exactly the curriculum.",
    strengths: "Crisis competence, depth intimacy, investment instinct, regenerative power.",
    weaknesses: "Control struggles, secrecy, entanglement in others' resources or dramas.",
    lifeLessons: "Letting what's dead die so what's next can arrive; merging without losing sovereignty.",
    opportunities: "Investing, estate and tax strategy, psychology, transformation work, turnarounds.",
    blindSpots: "Unspoken financial entanglements and the power dynamics inside intimacy.",
    timing: "8th-house profection years (ages 7, 19, 31, 43, 55); Pluto/Saturn transits here mark the great metamorphoses.",
    evolution: "From fearing loss → mastering cycles → becoming someone crisis cannot bankrupt.",
    reflectionQuestions: ["What am I white-knuckling that wants to end?", "Where does money tie me to people in ways I haven't examined?"],
    practicalRecommendations: [
      "Get radically clean on shared finances: agreements in writing, debts scheduled, estate documents done.",
      "Do the depth work (therapy, shadow work) proactively — this house sends invoices for avoidance.",
    ],
  },
  9: {
    house: 9,
    name: "Expansion, Belief & Horizon",
    meaning: "Travel, higher education, publishing, law, philosophy, foreign cultures, and the meaning-making function.",
    psychology: "The stories you tell about how life works. Limiting beliefs are 9th-house infrastructure problems.",
    strengths: "Vision, teaching ability, cross-cultural fluency, luck that follows faith.",
    weaknesses: "Dogma, over-promising, escaping the near via the far.",
    lifeLessons: "Earning your worldview through experience rather than inheriting it.",
    opportunities: "International markets, publishing, teaching, higher credentials, thought leadership.",
    blindSpots: "Which beliefs are actually yours versus absorbed from culture and family.",
    timing: "9th-house profection years (ages 8, 20, 32, 44, 56); Jupiter's returns to this house open expansion windows.",
    evolution: "From seeking answers → building a philosophy → living it so clearly others learn by watching.",
    reflectionQuestions: ["What belief, if I dropped it, would change everything downstream?"],
    practicalRecommendations: [
      "Take the trip that scares you a little; this house converts distance into wisdom.",
      "Teach what you know at every level — the 9th house monetizes synthesis.",
    ],
  },
  10: {
    house: 10,
    name: "Career, Reputation & Legacy",
    meaning: "Vocation, public standing, authority, achievement, and what you'll be remembered for. The mountain peak.",
    psychology: "The internalized authority figure. How you relate to bosses, ambition, and being judged in public all live here.",
    strengths: "Executive capacity, strategic patience, the ability to carry public responsibility.",
    weaknesses: "Achievement addiction, fear of visible failure, borrowing goals from parents or culture.",
    lifeLessons: "Climbing your own mountain — discovering the summit you actually want before spending decades on the wrong ascent.",
    opportunities: "Leadership roles, public authority, building institutions and reputations that compound.",
    blindSpots: "The cost your ambition bills to the 4th house (home, family, inner life).",
    timing: "10th-house profection years (ages 9, 21, 33, 45, 57); Saturn crossing your Midheaven is the career reckoning-and-crowning transit.",
    evolution: "From proving yourself → mastering your craft → building things that outlast you.",
    reflectionQuestions: ["Whose definition of success am I actually pursuing?", "What do I want said about my work when I'm gone?"],
    practicalRecommendations: [
      "Optimize for reputation-compounding work: fewer, more visible, more excellent projects.",
      "Review your trajectory every Saturn milestone (ages ~29, ~44, ~58) — these are natural pivot points.",
    ],
  },
  11: {
    house: 11,
    name: "Networks, Community & Future Vision",
    meaning: "Friends, allies, audiences, communities, social causes, and gains from career. Your people, plural.",
    psychology: "Belonging beyond family. Wounds here show as never quite fitting the group — which often marks the person meant to build a new one.",
    strengths: "Coalition-building, audience growth, futurist instinct, friendship as wealth.",
    weaknesses: "Losing individuality to the tribe, or exiling yourself entirely from it.",
    lifeLessons: "Finding — or founding — the room where you don't have to shrink.",
    opportunities: "Community businesses, audiences and platforms, movements, angel networks.",
    blindSpots: "Your network's ceiling becomes yours; audit who's actually in the room.",
    timing: "11th-house profection years (ages 10, 22, 34, 46, 58); Jupiter here delivers allies and audience jumps.",
    evolution: "From wanting to belong → curating your circle → convening people around a shared future.",
    reflectionQuestions: ["Who are my five most-contacted people, and are they pulling me forward?"],
    practicalRecommendations: [
      "Invest in community deliberately: host, convene, introduce — the 11th house pays connectors.",
      "Build the audience before you need it; distribution is a long game.",
    ],
  },
  12: {
    house: 12,
    name: "The Unseen: Retreat, Endings & Transcendence",
    meaning: "Solitude, the unconscious, institutions, hidden things, self-undoing patterns, spirituality, and work done behind the scenes.",
    psychology: "The basement archive: everything exiled from consciousness. Self-sabotage is 12th-house material asking for daylight.",
    strengths: "Imagination, compassion, spiritual depth, the ability to work invisibly on what matters.",
    weaknesses: "Escapism, martyrdom, secret self-defeat, boundary dissolution.",
    lifeLessons: "Making the unconscious conscious before it makes your decisions for you.",
    opportunities: "Research, healing arts, spiritual practice, behind-the-scenes power, creative solitude.",
    blindSpots: "By definition — this house is your blind spot. Dreams, slips and repeating 'bad luck' are its memos.",
    timing: "12th-house profection years (ages 11, 23, 35, 47, 59) are closing chapters: finish, grieve, rest, release.",
    evolution: "From being run by the hidden → befriending it → drawing creative and spiritual power from the deep.",
    reflectionQuestions: ["What pattern do I call bad luck that is actually a decision I keep making?"],
    practicalRecommendations: [
      "Build a daily solitude practice (meditation, journaling, walks) — this house rewards it with clarity and sleep.",
      "Before every new chapter, formally close the old one; unfinished endings leak into new beginnings.",
    ],
  },
};

export interface PlanetDeepDive {
  body: Body;
  purpose: string;
  healthyExpression: string;
  shadowExpression: string;
  needs: string;
  lifeLesson: string;
  careerImpact: string;
  relationshipImpact: string;
  moneyImpact: string;
  leadershipStyle: string;
  stressBehavior: string;
  healing: string;
}

export const PLANET_DEEP_DIVES: Partial<Record<Body, PlanetDeepDive>> = {
  Sun: {
    body: "Sun",
    purpose: "Your core identity and life force — the hero of the chart's story and what you are here to become.",
    healthyExpression: "Confident self-authorship, warmth, creative vitality, dependable radiance.",
    shadowExpression: "Ego inflation, approval addiction, or the opposite: dimming yourself to keep others comfortable.",
    needs: "Recognition for who you actually are, creative outlets, a mission worthy of your vitality.",
    lifeLesson: "Shine as yourself, not as applause requires.",
    careerImpact: "Its sign and house show where you must be visible and self-directed to feel alive at work.",
    relationshipImpact: "Partners must respect your essential self; relationships that require self-erasure will fail.",
    moneyImpact: "Income grows when tied to identity-aligned work; soul-less work caps earnings and health together.",
    leadershipStyle: "Leads by presence and example; the room organizes around a healthy Sun.",
    stressBehavior: "Pride spirals, drama, or collapse into invisibility.",
    healing: "Sunlight, creative practice, and doing one thing daily that is unmistakably yours.",
  },
  Moon: {
    body: "Moon",
    purpose: "Your emotional operating system — needs, instincts, memory, and how you self-soothe.",
    healthyExpression: "Emotional fluency, intuitive accuracy, the capacity to nurture and be nurtured.",
    shadowExpression: "Moodiness weaponized, emotional eating/spending, caretaking as control.",
    needs: "Safety, rhythm, belonging, and permission to feel without fixing.",
    lifeLesson: "Meeting your own needs directly instead of hoping others guess them.",
    careerImpact: "Shows the emotional conditions required to do your best work; ignore them and productivity mysteriously dies.",
    relationshipImpact: "The Moon is what 3 a.m. you needs from a partner — compatibility here outweighs almost everything.",
    moneyImpact: "Spending soothes lunar wounds; budget for comfort consciously or it will budget itself.",
    leadershipStyle: "Leads by attunement — reads the room before the spreadsheet.",
    stressBehavior: "Withdrawal, clinginess, or regression to childhood coping.",
    healing: "Water, consistent sleep, tending something living, and naming feelings out loud.",
  },
  Mercury: {
    body: "Mercury",
    purpose: "The mind's messenger — how you think, learn, speak, write, trade, and connect dots.",
    healthyExpression: "Clear articulate thought, curiosity, wit, skillful negotiation.",
    shadowExpression: "Overthinking, gossip, cleverness without wisdom, information hoarding.",
    needs: "Mental stimulation, conversation, variety, and things worth explaining.",
    lifeLesson: "Aligning words with truth — saying what you mean and meaning what you say.",
    careerImpact: "Its condition sets your communication ceiling: writing, selling, coding, teaching all run through Mercury.",
    relationshipImpact: "You bond through conversation as much as touch; verbal chemistry is real chemistry.",
    moneyImpact: "Deals, contracts, and negotiation outcomes live here — sharpen it and income follows.",
    leadershipStyle: "Leads by clarity: the one who can explain wins the room.",
    stressBehavior: "Mental loops, scattered starts, saying too much.",
    healing: "Journaling, single-tasking, walks without podcasts.",
  },
  Venus: {
    body: "Venus",
    purpose: "The attraction principle — love, beauty, pleasure, values, and what you draw toward you.",
    healthyExpression: "Warm relating, aesthetic intelligence, healthy receiving, gracious boundaries.",
    shadowExpression: "People-pleasing, luxury as anesthesia, self-worth outsourced to being chosen.",
    needs: "Beauty, affection, harmony, and pleasure without guilt.",
    lifeLesson: "You attract what you believe you deserve — upgrade the belief, not just the strategy.",
    careerImpact: "Governs design sense, diplomacy, client charm, and the careers where taste is the product.",
    relationshipImpact: "Your love language and attachment aesthetics; its aspects narrate your romantic pattern.",
    moneyImpact: "Venus IS the money planet: earning through attraction, art, relationship, and perceived value.",
    leadershipStyle: "Leads by magnetism and fairness; builds loyalty instead of demanding it.",
    stressBehavior: "Retail therapy, sugar, appeasement, aesthetic perfectionism.",
    healing: "Beauty on purpose: art, music, touch, and receiving compliments without deflecting.",
  },
  Mars: {
    body: "Mars",
    purpose: "The drive system — desire, courage, aggression, and the capacity to go get it.",
    healthyExpression: "Clean assertion, decisive action, protective courage, athletic vitality.",
    shadowExpression: "Rage leaks, passive aggression, recklessness, or desire turned inward as self-attack.",
    needs: "Physical outlets, worthy challenges, and permission to want what you want.",
    lifeLesson: "Anger is information and fuel — neither suppress it nor hand it the wheel.",
    careerImpact: "Sets your competitive style and stamina; its house shows where you fight best.",
    relationshipImpact: "Sexual signature and conflict style; suppressed Mars kills desire faster than any argument.",
    moneyImpact: "Earning through initiative and nerve; also the impulse-purchase and rash-risk planet.",
    leadershipStyle: "Leads from the front; best in campaigns, launches, and turnarounds.",
    stressBehavior: "Irritability, picking fights, injury-prone haste — or total stall.",
    healing: "Hard exercise, competition with rules, and saying the direct thing kindly.",
  },
  Jupiter: {
    body: "Jupiter",
    purpose: "The expansion principle — growth, faith, luck, meaning, and the size of life you'll permit yourself.",
    healthyExpression: "Optimism with receipts, generosity, vision, teaching, well-timed risk.",
    shadowExpression: "Overextension, empty hype, promising beyond capacity, philosophical arrogance.",
    needs: "Room to grow, meaning, adventure, and something to believe in.",
    lifeLesson: "Discern which opportunities are yours — Jupiter opens every door; wisdom is choosing.",
    careerImpact: "Where Jupiter sits, doors open with less effort — build your growth strategy around its house.",
    relationshipImpact: "Generosity and shared philosophy; partners must share your appetite for growth.",
    moneyImpact: "The abundance channel: earning scales when you teach, publish, expand internationally, or bet on growth.",
    leadershipStyle: "Leads by vision and morale; the chief-encouragement officer.",
    stressBehavior: "Overcommitting, escapist optimism, gambling the surplus.",
    healing: "Gratitude with specificity, travel, mentoring someone behind you.",
  },
  Saturn: {
    body: "Saturn",
    purpose: "The architect — structure, discipline, time, mastery, and earned authority.",
    healthyExpression: "Reliability, patient craftsmanship, wise boundaries, institutional competence.",
    shadowExpression: "Fear masquerading as realism, harsh inner critic, control, chronic postponement of joy.",
    needs: "Respect, tangible progress, and standards worth meeting.",
    lifeLesson: "Where Saturn sits is where you feel behind — and where devoted practice makes you the authority by midlife.",
    careerImpact: "Your mastery zone and your imposter syndrome share an address; the fear marks the vocation.",
    relationshipImpact: "Commitment style and walls; love here is proven in consistency, not declarations.",
    moneyImpact: "Wealth by compounding: slow, structural, unglamorous, and ultimately the largest.",
    leadershipStyle: "Leads by standards and dependability; the one still there when it's hard.",
    stressBehavior: "Rigidity, isolation, workaholism, pessimism presented as prudence.",
    healing: "Kind discipline: small kept promises to yourself, and mercy for the decade it takes.",
  },
  Uranus: {
    body: "Uranus",
    purpose: "The awakener — freedom, originality, disruption, and your genius deviation from the norm.",
    healthyExpression: "Innovation, authentic rebellion, future-sight, liberating others by example.",
    shadowExpression: "Chaos addiction, contrarianism as identity, detachment from feeling, burning what needed renovation.",
    needs: "Autonomy, novelty, and room to be strange.",
    lifeLesson: "True freedom is self-authorship, not mere opposition.",
    careerImpact: "Marks where you innovate and can't tolerate business-as-usual — technology, reinvention, disruption.",
    relationshipImpact: "Needs space inside intimacy; partners who require sameness will trigger the ejector seat.",
    moneyImpact: "Windfalls and reversals; income from innovation, tech, and being early.",
    leadershipStyle: "Leads by breakthrough; better revolutionary than administrator.",
    stressBehavior: "Sudden exits, insomnia, nervous-system overload.",
    healing: "Scheduled freedom, experimental projects, nervous-system care.",
  },
  Neptune: {
    body: "Neptune",
    purpose: "The dissolver — imagination, compassion, spirituality, and the longing for the boundless.",
    healthyExpression: "Artistic vision, empathy, spiritual connection, healing presence.",
    shadowExpression: "Escapism, deception (of self first), martyrdom, addictive anesthesia.",
    needs: "Transcendence on purpose: art, ocean, prayer, music — or it will be sought through fog.",
    lifeLesson: "Discernment: keeping the compassion while dropping the illusion.",
    careerImpact: "Where you're touched by inspiration — creative and healing fields shine; contracts here need extra clarity.",
    relationshipImpact: "Romantic idealization zone: you fall in love with potential; verify the actual.",
    moneyImpact: "Financial fog risk — automate, document, and audit anything Neptune touches.",
    leadershipStyle: "Leads by inspiration and story; needs a Saturn lieutenant.",
    stressBehavior: "Checking out: screens, substances, sleep, fantasy.",
    healing: "Water, music, service, and creative practice with a container.",
  },
  Pluto: {
    body: "Pluto",
    purpose: "The transformer — power, depth, death-and-rebirth, and what refuses to stay superficial.",
    healthyExpression: "Regenerative power, psychological depth, fearless honesty, phoenix resilience.",
    shadowExpression: "Control, manipulation, obsession, power struggles, scorched-earth endings.",
    needs: "Depth, truth, and periodic reinvention.",
    lifeLesson: "Power over yourself, not others; what you face transforms, what you bury runs you.",
    careerImpact: "Marks where you can wield real influence — research, finance, psychology, crisis leadership.",
    relationshipImpact: "All-or-nothing intimacy; trust is the currency and betrayal the deepest wound.",
    moneyImpact: "Other people's money, leverage, and transformational bets; power dynamics shadow joint finances.",
    leadershipStyle: "Leads through intensity and strategy; transformational, not transactional.",
    stressBehavior: "Control tightening, secrecy, ruminating on betrayals.",
    healing: "Shadow work, honest confession, ritual endings, strength training.",
  },
  Chiron: {
    body: "Chiron",
    purpose: "The wounded healer — the injury that never fully closes and becomes your medicine for others.",
    healthyExpression: "Mentorship born of scar tissue; healing skill exactly where you were hurt.",
    shadowExpression: "Identifying as broken; healing everyone but yourself.",
    needs: "Compassionate witness, and usefulness for the pain.",
    lifeLesson: "The wound is not your fault and is your responsibility — and, transformed, your gift.",
    careerImpact: "Practitioners, teachers and guides are made here; your credibility comes from having lived it.",
    relationshipImpact: "The tender spot partners will accidentally press; name it early.",
    moneyImpact: "Often a money/worth wound when in 2nd/8th — heal the story to unblock the flow.",
    leadershipStyle: "Leads with humility and hard-won empathy.",
    stressBehavior: "Old wound re-opens; shame spiral.",
    healing: "Turning the wound outward as service — teach what broke you.",
  },
};

export interface SignDeepDive {
  sign: Sign;
  healthyTraits: string;
  shadowTraits: string;
  communicationStyle: string;
  conflictStyle: string;
  datingStyle: string;
  businessStyle: string;
  moneyStyle: string;
  leadership: string;
  friendship: string;
  growth: string;
}

export const SIGN_DEEP_DIVES: Record<Sign, SignDeepDive> = {
  Aries: {
    sign: "Aries",
    healthyTraits: "Courageous, direct, self-starting, honest, energizing.",
    shadowTraits: "Impatient, combative, impulsive, starts more than it finishes.",
    communicationStyle: "Blunt and fast; says the thing others are circling.",
    conflictStyle: "Ignites quickly, burns out quickly, rarely holds grudges.",
    datingStyle: "The chase is real; keeps passion alive through challenge and freshness.",
    businessStyle: "Launcher and first-mover; needs lieutenants for the long middle.",
    moneyStyle: "Earns boldly, spends impulsively; automate the boring parts.",
    leadership: "Leads the charge from the front; inspires by fearlessness.",
    friendship: "Loyal, fun, up-for-anything; allergic to passive aggression.",
    growth: "Learning that patience is a weapon too — finishing is the new starting.",
  },
  Taurus: {
    sign: "Taurus",
    healthyTraits: "Steady, sensual, loyal, patient, quality-obsessed.",
    shadowTraits: "Stubborn, possessive, comfort-trapped, change-averse.",
    communicationStyle: "Deliberate and grounded; slow to speak, means what it says.",
    conflictStyle: "Immovable object; avoids fights, then digs in completely.",
    datingStyle: "Slow-burn devotion; shows love through consistency and pleasure.",
    businessStyle: "Builds durable value; excellent with assets, product quality, patience plays.",
    moneyStyle: "Natural accumulator; watch comfort spending on food, luxury and 'deserved' treats.",
    leadership: "Leads by reliability; the calm center in volatility.",
    friendship: "Few, deep, decades-long; the friend with the good table.",
    growth: "Security is inside; loosening the grip invites the abundance it clutches for.",
  },
  Gemini: {
    sign: "Gemini",
    healthyTraits: "Curious, witty, adaptable, connective, endlessly interesting.",
    shadowTraits: "Scattered, inconsistent, gossipy, surface-skating.",
    communicationStyle: "Sparkling, fast, wordplay-rich; thinks by talking.",
    conflictStyle: "Debates rather than fights; can argue both sides and forget which is theirs.",
    datingStyle: "Mental chemistry first; boredom is the only real dealbreaker.",
    businessStyle: "Media, sales, ideas, networks; monetizes information flow.",
    moneyStyle: "Multiple streams, variable discipline; needs one boring anchor account.",
    leadership: "Leads by communication; translates between silos.",
    friendship: "Knows everyone; the human group chat.",
    growth: "Depth: choosing one thread and following it past the exciting part.",
  },
  Cancer: {
    sign: "Cancer",
    healthyTraits: "Nurturing, intuitive, tenacious, protective, memory-keeper.",
    shadowTraits: "Moody, indirect, clingy, retreats into the shell mid-conversation.",
    communicationStyle: "Emotional subtext everywhere; hears what isn't said.",
    conflictStyle: "Sideways — withdrawal and tone; must practice direct asks.",
    datingStyle: "All-in caretaker seeking emotional home; tests before trusting.",
    businessStyle: "Builds family-like teams and customer loyalty; hospitality, home, food, care sectors.",
    moneyStyle: "Saves for security; emotional spending when unmoored.",
    leadership: "Leads by care; people would run through walls for a healthy Cancer boss.",
    friendship: "The one who remembers your mother's surgery date.",
    growth: "Self-nurture first; the shell opens from the inside.",
  },
  Leo: {
    sign: "Leo",
    healthyTraits: "Radiant, generous, loyal, creative, big-hearted.",
    shadowTraits: "Pride, drama, approval-hunger, sulking when unlit.",
    communicationStyle: "Warm and theatrical; a natural storyteller.",
    conflictStyle: "Roars, then forgives; wounded pride is the real injury.",
    datingStyle: "Grand romance; loyal once genuinely adored.",
    businessStyle: "Brand, stage, leadership; the face of the enterprise.",
    moneyStyle: "Generous to a fault; earns big for the joy of giving big.",
    leadership: "Natural monarch; leads by heart and spectacle.",
    friendship: "Sunshine and fierce loyalty; celebrates your wins loudly.",
    growth: "Shine that doesn't need an audience is the mastered Leo.",
  },
  Virgo: {
    sign: "Virgo",
    healthyTraits: "Precise, helpful, discerning, competent, quietly devoted.",
    shadowTraits: "Critical (self first), anxious, perfectionist paralysis.",
    communicationStyle: "Exact and useful; edits while listening.",
    conflictStyle: "Critique volleys; must lead with appreciation to be heard.",
    datingStyle: "Love as acts of service; notices everything, needs to feel useful.",
    businessStyle: "Operations, quality, analysis; makes everything actually work.",
    moneyStyle: "Spreadsheet-native; frugal except for tools and health.",
    leadership: "Leads by competence; the standard-setter.",
    friendship: "The one who shows up with soup and a checklist.",
    growth: "Done is holy; perfection is procrastination in a lab coat.",
  },
  Libra: {
    sign: "Libra",
    healthyTraits: "Diplomatic, fair, charming, aesthetic, bridge-building.",
    shadowTraits: "Indecisive, conflict-avoidant, outsources identity to partners.",
    communicationStyle: "Graceful and calibrated; softens truths — sometimes too much.",
    conflictStyle: "Peace at any price until the ledger of resentments tips.",
    datingStyle: "Partnership-oriented romantic; in love with love; must keep a self.",
    businessStyle: "Deals, design, diplomacy; wins by relationships and taste.",
    moneyStyle: "Spends on beauty and others; needs decision rules to stop option paralysis.",
    leadership: "Leads by consensus and fairness; the great negotiator.",
    friendship: "Socially gifted; makes everyone feel considered.",
    growth: "Your preference is not rude — decide, disappoint, survive it.",
  },
  Scorpio: {
    sign: "Scorpio",
    healthyTraits: "Intense, loyal, perceptive, transformative, unflinching.",
    shadowTraits: "Suspicious, controlling, vengeful, secretive.",
    communicationStyle: "Strategic disclosure; says 20%, knows 100%.",
    conflictStyle: "Cold war and precision strikes; forgiveness is the frontier.",
    datingStyle: "All or nothing; tests loyalty covertly; unmatched depth once safe.",
    businessStyle: "Strategy, turnarounds, other people's money; plays long games.",
    moneyStyle: "Private and shrewd; power and money intertwine.",
    leadership: "Leads by gravity; commands without volume.",
    friendship: "Few vault-grade bonds; betrayal is unforgotten.",
    growth: "Vulnerability on purpose — trust extended is power, not weakness.",
  },
  Sagittarius: {
    sign: "Sagittarius",
    healthyTraits: "Optimistic, adventurous, philosophical, funny, freedom-loving.",
    shadowTraits: "Blunt to a fault, overpromising, commitment-skittish, preachy.",
    communicationStyle: "Big-picture and unfiltered; accidentally profound, occasionally tactless.",
    conflictStyle: "Laughs it off or leaves; struggles to sit in discomfort.",
    datingStyle: "Partner-in-adventure wanted; cages provoke escapes.",
    businessStyle: "Vision, expansion, international, teaching; sells the future.",
    moneyStyle: "Feast-or-famine optimism; needs automatic guardrails.",
    leadership: "Leads by vision and morale; the meaning-maker.",
    friendship: "The travel buddy and truth-teller.",
    growth: "Freedom deepens when you stay through chapter two.",
  },
  Capricorn: {
    sign: "Capricorn",
    healthyTraits: "Disciplined, strategic, dependable, dry-humored, built for the long climb.",
    shadowTraits: "Cold pragmatism, status-chasing, joy deferred to a retirement that never comes.",
    communicationStyle: "Economical and outcome-focused; respect is the love language.",
    conflictStyle: "Composed and positional; wins by outlasting.",
    datingStyle: "Vets like a CFO; slow, serious, then bedrock-loyal.",
    businessStyle: "Institution-builder; masters structures, timing, and power.",
    moneyStyle: "Compounding-native; the wealthiest sign given time.",
    leadership: "Leads by competence and endurance; authority earned, not claimed.",
    friendship: "Understated devotion; shows up in crises with a plan.",
    growth: "The summit is nicer with people on it; schedule the joy too.",
  },
  Aquarius: {
    sign: "Aquarius",
    healthyTraits: "Original, humanitarian, principled, future-fluent, unswayed by trends.",
    shadowTraits: "Detached, contrarian, intellectualizes feelings, superior-alien mode.",
    communicationStyle: "Conceptual and candid; debates ideas, not people.",
    conflictStyle: "Goes cerebral and distant; must return to the body to resolve.",
    datingStyle: "Friendship first; needs freedom and a partner who's also interesting.",
    businessStyle: "Innovation, networks, systems for many; monetizes the future early.",
    moneyStyle: "Unconventional streams; indifferent to status spending, funds the mission.",
    leadership: "Leads by ideas and ideals; reforms rather than rules.",
    friendship: "The whole-network friend; loyal to the group's vision.",
    growth: "The revolution includes your own heart — feel it, don't just theorize it.",
  },
  Pisces: {
    sign: "Pisces",
    healthyTraits: "Compassionate, imaginative, intuitive, artistic, boundlessly kind.",
    shadowTraits: "Escapist, boundary-less, martyred, fantasy-prone.",
    communicationStyle: "Impressionistic and empathic; feels the conversation more than parses it.",
    conflictStyle: "Absorbs, avoids, dissolves; needs words for the ocean inside.",
    datingStyle: "Romantic mystic; loves the soul, must also date the actual person.",
    businessStyle: "Creative and healing enterprises; vision supreme, needs operational ballast.",
    moneyStyle: "Porous — money flows out with feelings; automate everything.",
    leadership: "Leads by empathy and imagination; the culture's conscience.",
    friendship: "The 2 a.m. soul-call friend.",
    growth: "Boundaries are the banks that let the river run powerful and clear.",
  },
};
